### ISSUE TITLE
uupd.bin

### ISSUE THREAD

**Issue by jasc76** [d-ronin/openlager#57]
Hi

my lager worked fine all along, but now suddenly it just writes a uupd.bin file on the sd and nothing else ... ?
It also deletes my lager.cfg file. 
Help :-(

Regards
Jan

**Comment by mlyle** [comment]
Openlager won't write an uupd.bin file.  This is discussed as a failure mode of clone / counterfeit SD cards-- people have seen this with other things that use SD cards:

https://www.reddit.com/r/Bittboy/comments/ihf67i/pgv1_sd_card_stopped_working_not_missing_cfw/
