### ISSUE TITLE
Problem with Openlager

### ISSUE THREAD

**Issue by rs3hc** [d-ronin/openlager#58]
Sorry for posting it as a issue here but i cant find any detailed informations on the web.

i got a openlager from a buddy for logging a Betafpv Toothpick F722 2-6S AIO Brushless Flight Controller 35A(BLHeli_S) which dont offer storage...

I soldered 5V, GND and TX6 from FC to RX on openlager.
In Betafligth i configured UART6 as Blackbox logger ans 2000000 baud, ans Serials Logger, 2khz and Gyro_Scaled in the Blackbox section.
Should be ok...

I tried multipe SD Cards from Class4 over U1 32GB to U3 64GB A2 V30.... also tried all formats FAT/FAT32
Nothing works...

If i Power the FC the green LED on Openlager lit up correctly but the red LED (should be for write process?) never lit up.

Can anybody discripe how it should look like if it will work?

**Comment by maciejlagowski** [comment]
same issue here, tried different SD cards, different file formats etc..

**Comment by Zuldan** [comment]
I don’t know the answer to your issues but if you guys also mention which Openlager chip you are using it may help in the diagnosis. As far as I know there is an Airbot and JHEMCU version, possibly others exist…

**Comment by maciejlagowski** [comment]
Mine is Airbot Openlager

**Comment by rs3hc** [comment]
![IMG_20220411_150046](https://user-images.githubusercontent.com/69956680/162745460-6861cfe2-ac30-4c7e-bf39-88a6d691c530.jpg)

**Comment by maciejlagowski** [comment]
My problem was solved by inserting a card with the lager.bin file to flash. Surprisingly now the device works :)

**Comment by rs3hc** [comment]
> My problem was solved by inserting a card with the lager.bin file to flash. Surprisingly now the device works :)

Only "lager.bin"?
How long did it take?
What did the red LED while updating?

For what do we need these two other files? (bootlager.bin, ef_lager.bin)

**Comment by maciejlagowski** [comment]
> > My problem was solved by inserting a card with the lager.bin file to flash. Surprisingly now the device works :)
> 
> Only "lager.bin"? How long did it take? What did the red LED while updating?
> 
> For what do we need these two other files? (bootlager.bin, ef_lager.bin)

I put only lager.bin file on the SD, red LED was flashing for about 20 seconds maybe, then I powered it off and checked the SD card - there was config and log file.

**Comment by rs3hc** [comment]
Oh OK..

I tried 3 sd cards with lager.bin and nothing happened. Only green Led was on

**Comment by rs3hc** [comment]
Any one can help??
