### ISSUE TITLE
Witch firmware shold I flash?

### ISSUE THREAD

**Issue by sanmaodeai** [d-ronin/openlager#61]
Hello guys, I make a openlarger hardware ,but I don't know witch firmware should I flash ?
bootlager.bin ,  ef_lager.bin  , lager.bin
witch one should I flash?
I want use this hardware for  the BF's blackbox recoder . Use serial to communication.

**Comment by mlyle** [comment]
ef_lager.bin is the entire flash image, including the bootloader (bootlager.bin) & the firmware (lager.bin).

The update process uses a lager.bin.

**Comment by sanmaodeai** [comment]
> ef_lager.bin is the entire flash image, including the bootloader (bootlager.bin) & the firmware (lager.bin).
> 
> The update process uses a lager.bin.

thanks for your reply.And if I flash the  ef_lager.bin , the start address is 0x8000000?
